// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2;
using YourNamespace.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231020091110_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BibliotekaKsiazki", b =>
                {
                    b.Property<int>("BibliotekaId")
                        .HasColumnType("int");

                    b.Property<int>("KsiazkiId")
                        .HasColumnType("int");

                    b.HasKey("BibliotekaId", "KsiazkiId");

                    b.HasIndex("KsiazkiId");

                    b.ToTable("BibliotekaKsiazki");
                });

            modelBuilder.Entity("WebApplication2.Biblioteka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Biblioteka");
                });

            modelBuilder.Entity("WebApplication2.Ksiazki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("rok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ksiazki");
                });

            modelBuilder.Entity("BibliotekaKsiazki", b =>
                {
                    b.HasOne("WebApplication2.Biblioteka", null)
                        .WithMany()
                        .HasForeignKey("BibliotekaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Ksiazki", null)
                        .WithMany()
                        .HasForeignKey("KsiazkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
